# Generated by Django 4.0.2 on 2022-02-19 16:19

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=150, verbose_name='Марка')),
                ('car_model', models.CharField(max_length=200, verbose_name='Модель')),
                ('vehicle_num', models.CharField(max_length=12, verbose_name='Гос номер')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Машины',
                'verbose_name_plural': 'Машины',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('patronymic', models.CharField(max_length=100, null=True, verbose_name='Отчество')),
                ('phoneNumber', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Номер телефона')),
                ('finding_from', models.TextField(verbose_name='Откуда нашли')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('car', models.ManyToManyField(to='shinka_app.Car')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['surname'],
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_work', models.BooleanField(default=False, verbose_name='Прибытие на обслуживание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания заяви')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата и время обновления заявки')),
                ('date_of_work', models.DateField(verbose_name='Дата проведения работы')),
                ('approximate_begin_time', models.DateTimeField(verbose_name='Предположительное время начала работы')),
                ('real_begin_time', models.TimeField(null=True, verbose_name='Реальное время начала работы')),
                ('end_time', models.TimeField(null=True, verbose_name='Время окончания работы')),
                ('extra_price', models.FloatField(verbose_name='Дополнительная стоимость')),
                ('comment', models.TextField(verbose_name='Комментарий к работе')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shinka_app.car', verbose_name='Машина')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shinka_app.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'История работ',
                'verbose_name_plural': 'История работ',
                'ordering': ['approximate_begin_time'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Должность')),
                ('price', models.IntegerField(verbose_name='Ставка (р/час)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_work', models.DateField(verbose_name='Дата работы')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписание',
                'ordering': ['date_of_work'],
            },
        ),
        migrations.CreateModel(
            name='ServiceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название услуги')),
                ('price', models.IntegerField(verbose_name='Стоимость')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(max_length=150, verbose_name='Тип')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('defaul_price', models.IntegerField(verbose_name='Закупочная цена')),
                ('sale_price', models.IntegerField(null=True, verbose_name='Стоимость продажи')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товар',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('patronymic', models.CharField(max_length=100, null=True, verbose_name='Отчество')),
                ('phoneNumber', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Номер телефона')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shinka_app.position', verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Рабочий',
                'verbose_name_plural': 'Должности',
                'ordering': ['surname'],
            },
        ),
        migrations.CreateModel(
            name='WorkerSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance', models.BooleanField(verbose_name='Выход на работу')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shinka_app.schedule', verbose_name='График')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shinka_app.worker', verbose_name='Рабочий')),
            ],
            options={
                'verbose_name': 'График',
                'verbose_name_plural': 'График',
            },
        ),
        migrations.CreateModel(
            name='WheelsCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=150, verbose_name='Модель')),
                ('diametr', models.IntegerField(verbose_name='Диаметр')),
                ('width', models.IntegerField(verbose_name='Ширина')),
                ('profile', models.IntegerField(verbose_name='Профиль')),
                ('run_flat', models.BooleanField(verbose_name='Run flat')),
                ('marking_c', models.BooleanField(verbose_name='Маркировка С')),
                ('status', models.CharField(max_length=150, verbose_name='Статус')),
                ('stock_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shinka_app.stocktype', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Шина',
                'verbose_name_plural': 'Шины',
                'ordering': ['model_name'],
            },
        ),
        migrations.CreateModel(
            name='StockHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='Количество товара для услуги')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shinka_app.stocktype', verbose_name='Товар')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shinka_app.history', verbose_name='Работа')),
            ],
            options={
                'verbose_name': 'Количество тоавара для услуги',
                'verbose_name_plural': 'Количество товара для услуги',
                'ordering': ['quantity'],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата операции')),
                ('number', models.IntegerField(verbose_name='Количество')),
                ('stock_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shinka_app.stocktype', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Запись со склада',
                'verbose_name_plural': 'Записи со склада',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='ServiceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='Количество оказанных услуг')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shinka_app.servicelist', verbose_name='Услуга')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shinka_app.history', verbose_name='Работа')),
            ],
            options={
                'verbose_name': 'Количество услуг',
                'verbose_name_plural': 'Количество услуг',
                'ordering': ['work'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.FloatField(verbose_name='Оценка')),
                ('comment', models.TextField(verbose_name='Комментарий к оценке')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shinka_app.client', verbose_name='Клиент')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shinka_app.history', verbose_name='Работа')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PositionChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время смены должности')),
                ('new_position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shinka_app.position', verbose_name='Должность')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shinka_app.worker', verbose_name='рабочий')),
            ],
            options={
                'verbose_name': 'Смена должности',
                'verbose_name_plural': 'Смены должностей',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='history',
            name='main_worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shinka_app.worker', verbose_name='Главный рабочий'),
        ),
        migrations.CreateModel(
            name='BonusFine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время назначения премии/штрафа')),
                ('price', models.IntegerField(default=0, verbose_name='Стоимость')),
                ('comment', models.TextField(null=True, verbose_name='Коммментарий к шрафу/премии')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shinka_app.worker', verbose_name='Рабочий')),
            ],
            options={
                'verbose_name': 'Штраф/премия',
                'verbose_name_plural': 'Штрафы/премии',
                'ordering': ['date'],
            },
        ),
    ]
