# Generated by Django 4.0.2 on 2022-02-20 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shinka_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockhistory',
            options={'ordering': ['work'], 'verbose_name': 'Количество тоавара для услуги', 'verbose_name_plural': 'Количество товара для услуги'},
        ),
        migrations.AlterModelOptions(
            name='worker',
            options={'ordering': ['surname'], 'verbose_name': 'Рабочий', 'verbose_name_plural': 'Рабочие'},
        ),
        migrations.AddField(
            model_name='wheelscharacter',
            name='grade',
            field=models.FloatField(default=5.0, verbose_name='Оценка'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wheelscharacter',
            name='winter',
            field=models.BooleanField(default=True, verbose_name='Зима'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stocktype',
            name='sale_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Стоимость продажи'),
        ),
    ]
