# Generated by Django 4.0.2 on 2022-02-20 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shinka_app', '0002_alter_stockhistory_options_alter_worker_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockhistory',
            name='quantity',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Количество товара для услуги'),
        ),
    ]
