# Generated by Django 4.0.2 on 2022-02-21 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shinka_app', '0004_alter_client_patronymic_alter_worker_patronymic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий к работе'),
        ),
    ]
