# Generated by Django 4.0.2 on 2022-02-23 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shinka_app', '0006_alter_history_approximate_begin_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='shinka_app.servicehistory', verbose_name='Услуги'),
        ),
        migrations.AddField(
            model_name='history',
            name='stock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='shinka_app.stockhistory', verbose_name='Товары'),
        ),
    ]
