# Generated by Django 4.0.2 on 2022-02-26 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shinka_app', '0007_history_service_history_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockhistory',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='stockhistory',
            name='work',
        ),
        migrations.RemoveField(
            model_name='history',
            name='service',
        ),
        migrations.AddField(
            model_name='history',
            name='service',
            field=models.ManyToManyField(to='shinka_app.ServiceList'),
        ),
        migrations.RemoveField(
            model_name='history',
            name='stock',
        ),
        migrations.AddField(
            model_name='history',
            name='stock',
            field=models.ManyToManyField(to='shinka_app.StockType'),
        ),
        migrations.DeleteModel(
            name='ServiceHistory',
        ),
        migrations.DeleteModel(
            name='StockHistory',
        ),
    ]
