# Generated by Django 4.0.2 on 2022-02-26 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shinka_app', '0008_remove_stockhistory_stock_remove_stockhistory_work_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='service',
            field=models.ManyToManyField(blank=True, null=True, to='shinka_app.ServiceList'),
        ),
        migrations.AlterField(
            model_name='history',
            name='stock',
            field=models.ManyToManyField(blank=True, null=True, to='shinka_app.StockType'),
        ),
    ]
