# Generated by Django 4.0.2 on 2022-02-26 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shinka_app', '0009_alter_history_service_alter_history_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='service',
        ),
        migrations.RemoveField(
            model_name='history',
            name='stock',
        ),
        migrations.CreateModel(
            name='StockHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=1, null=True, verbose_name='Количество товара для услуги')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shinka_app.stocktype', verbose_name='Товар')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shinka_app.history', verbose_name='Работа')),
            ],
            options={
                'verbose_name': 'Количество тоавара для услуги',
                'verbose_name_plural': 'Количество товара для услуги',
                'ordering': ['work'],
            },
        ),
        migrations.CreateModel(
            name='ServiceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='Количество оказанных услуг')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shinka_app.servicelist', verbose_name='Услуга')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shinka_app.history', verbose_name='Работа')),
            ],
            options={
                'verbose_name': 'Количество услуг',
                'verbose_name_plural': 'Количество услуг',
                'ordering': ['work'],
            },
        ),
    ]
