# Generated by Django 4.0.2 on 2022-02-27 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shinka_app', '0011_rename_defaul_price_stocktype_default_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wheelscharacter',
            old_name='diametr',
            new_name='diameter',
        ),
    ]
