# Generated by Django 4.0.2 on 2022-02-28 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shinka_app', '0012_rename_diametr_wheelscharacter_diameter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wheelscharacter',
            name='stock_type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='shinka_app.stocktype', verbose_name='Товар'),
        ),
    ]
