# Generated by Django 4.0.2 on 2022-03-05 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shinka_app', '0013_alter_wheelscharacter_stock_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServiceHistory',
            new_name='ServiceWork',
        ),
        migrations.RenameModel(
            old_name='StockHistory',
            new_name='StockWork',
        ),
        migrations.RenameModel(
            old_name='History',
            new_name='Work',
        ),
    ]
