# Generated by Django 4.0.2 on 2022-03-09 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shinka_app', '0014_rename_servicehistory_servicework_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicework',
            options={'ordering': ['work'], 'verbose_name': 'Услуги в работе', 'verbose_name_plural': 'Услуги в работе'},
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ['date'], 'verbose_name': 'Склад', 'verbose_name_plural': 'Склад'},
        ),
        migrations.AlterModelOptions(
            name='stockwork',
            options={'ordering': ['work'], 'verbose_name': 'Товары для работы', 'verbose_name_plural': 'Товары для работы'},
        ),
        migrations.AlterModelOptions(
            name='wheelscharacter',
            options={'ordering': ['model_name'], 'verbose_name': 'Шина/Колесо', 'verbose_name_plural': 'Шины/Колеса'},
        ),
        migrations.AlterModelOptions(
            name='work',
            options={'ordering': ['approximate_begin_time'], 'verbose_name': 'Работа', 'verbose_name_plural': 'Работы'},
        ),
        migrations.AlterField(
            model_name='bonusfine',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bonus', to='shinka_app.worker', verbose_name='Рабочий'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock', to='shinka_app.stocktype', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='wheelscharacter',
            name='stock_type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='wheels', to='shinka_app.stocktype', verbose_name='Товар'),
        ),
    ]
