# Generated by Django 4.0.2 on 2022-03-10 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shinka_app', '0016_rename_wheelscharacter_wheels_alter_bonusfine_worker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wheels',
            name='stock_type',
        ),
        migrations.AddField(
            model_name='stock',
            name='wheels',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shinka_app.wheels', verbose_name='Шина'),
        ),
        migrations.AddField(
            model_name='wheels',
            name='brand',
            field=models.CharField(default='Mishlen', max_length=150, verbose_name='Марка'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wheels',
            name='type',
            field=models.CharField(default='Шина', max_length=6, verbose_name='Тип'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wheels',
            name='work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wheels', to='shinka_app.work', verbose_name='Работа'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock', to='shinka_app.stocktype', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='stockwork',
            name='stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shinka_app.stocktype', verbose_name='Товар'),
        ),
    ]
