# Generated by Django 4.0.2 on 2022-03-10 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shinka_app', '0017_remove_wheels_stock_type_stock_wheels_wheels_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='stock_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='shinka_app.stocktype', verbose_name='Товар'),
        ),
    ]
