# Generated by Django 4.0.2 on 2022-03-10 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shinka_app', '0018_alter_stock_stock_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='stock_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='shinka_app.stocktype', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='wheels',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shinka_app.wheels', verbose_name='Шина'),
        ),
    ]
