# Generated by Django 4.0.2 on 2022-03-10 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shinka_app', '0019_alter_stock_stock_type_alter_stock_wheels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wheels',
            name='work',
        ),
        migrations.AddField(
            model_name='wheels',
            name='work',
            field=models.ManyToManyField(blank=True, null=True, related_name='wheels', to='shinka_app.Work', verbose_name='Работа'),
        ),
    ]
