# Generated by Django 4.0.2 on 2022-03-14 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shinka_app', '0021_wheels_default_price_wheels_sale_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='vehicle_num',
            field=models.CharField(max_length=12, unique=True, verbose_name='Гос номер'),
        ),
        migrations.AlterField(
            model_name='servicework',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service', to='shinka_app.work', verbose_name='Работа'),
        ),
        migrations.AlterField(
            model_name='work',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время окончания работы'),
        ),
        migrations.AlterField(
            model_name='work',
            name='extra_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Дополнительная стоимость'),
        ),
        migrations.AlterField(
            model_name='work',
            name='main_worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shinka_app.worker', verbose_name='Главный рабочий'),
        ),
        migrations.AlterField(
            model_name='work',
            name='real_begin_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Реальное время начала работы'),
        ),
    ]
