# Generated by Django 4.0.2 on 2022-03-16 12:45

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('shinka_app', '0022_alter_car_vehicle_num_alter_servicework_work_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='finding_from',
            field=models.TextField(blank=True, null=True, verbose_name='Откуда нашли'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phoneNumber',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='client',
            name='surname',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Фамилия'),
        ),
    ]
