# Generated by Django 4.0.2 on 2022-03-16 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shinka_app', '0024_alter_client_name_alter_client_surname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shinka_app.client', verbose_name='Клиент'),
        ),
    ]
