# Generated by Django 4.0.2 on 2022-03-20 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shinka_app', '0025_alter_work_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='stock',
            field=models.ManyToManyField(blank=True, null=True, to='shinka_app.StockType'),
        ),
        migrations.DeleteModel(
            name='StockWork',
        ),
    ]
