# Generated by Django 4.0.2 on 2022-03-20 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shinka_app', '0026_work_stock_delete_stockwork'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicework',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work', to='shinka_app.servicelist', verbose_name='Услуга'),
        ),
        migrations.AlterField(
            model_name='work',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shinka_app.client', verbose_name='Клиент'),
        ),
    ]
