# Generated by Django 4.0.2 on 2022-03-20 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shinka_app', '0027_alter_servicework_service_alter_work_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='client',
        ),
    ]
