# Generated by Django 4.0.2 on 2022-03-20 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shinka_app', '0028_remove_review_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerschedule',
            name='hours',
            field=models.IntegerField(default=10, verbose_name='Количество часов'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workerschedule',
            name='place',
            field=models.BooleanField(default=True, verbose_name='Главная точка шиномонтажа'),
            preserve_default=False,
        ),
    ]
