# Generated by Django 4.0.2 on 2022-04-07 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shinka_app', '0030_remove_workerschedule_schedule_workerschedule_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shinka_app.car', verbose_name='Машина'),
        ),
    ]
