# Generated by Django 4.0.2 on 2022-04-07 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shinka_app', '0031_alter_work_car'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['brand'], 'verbose_name': 'Машины', 'verbose_name_plural': 'Машины'},
        ),
        migrations.RemoveField(
            model_name='car',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='car',
            name='updated_at',
        ),
    ]
