# Generated by Django 4.0.2 on 2022-04-09 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shinka_app', '0032_alter_car_options_remove_car_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicework',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work', to='shinka_app.servicelist', verbose_name='Услуга'),
        ),
        migrations.AlterField(
            model_name='servicework',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service', to='shinka_app.work', verbose_name='Работа'),
        ),
    ]
