# Generated by Django 4.0.2 on 2022-04-14 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shinka_app', '0033_alter_servicework_service_alter_servicework_work'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wheels',
            name='work',
        ),
        migrations.AddField(
            model_name='work',
            name='wheels',
            field=models.ManyToManyField(blank=True, null=True, to='shinka_app.Wheels', verbose_name='Работа'),
        ),
    ]
